"""Daily briefing: Zebot's message, generated by Claude once a day."""

import json
import logging
from datetime import date

import anthropic

from .config import Difficulty, Settings
from .pet import PetState
from .vault.study import Roadmap
from .vault.tasks import Task

log = logging.getLogger(__name__)

MAX_TASKS_IN_PROMPT = 8
ACTIVITY_KINDS = {
    "task_done": "tarea cerrada en el vault",
    "capture": "se lo contó a Zebot (\"ya hice…\")",
}
WEEKDAYS = ["lunes", "martes", "miércoles", "jueves", "viernes", "sábado", "domingo"]

TONE = {
    "casual": "Sarcasmo suave. Recuerdas sin presionar y celebras cualquier avance.",
    "normal": "Sarcasmo cuando hay atraso, elogio exagerado cuando hay avance.",
    "hardcore": "Sarcasmo afilado y exigente. Le reclamas cada día sin avance, como un entrenador de speedrun.",
}

SYSTEM_PROMPT = """Eres {name}, la mascota virtual tipo Tamagotchi de Zeb. Vives en su escritorio y lo saludas al iniciar sesión.

Sobre Zeb: sysadmin de middleware en transición a Cloud Engineer (AWS). Le gustan los videojuegos y la tecnología. Estudia para la certificación AWS Cloud Practitioner y aprende Python.

Tu personalidad:
- Sarcástico y con jerga gamer (GG, farmear XP, AFK, boss final, nerf, buff, speedrun, respawn…). Te burlas con cariño; nunca humillas ni eres cruel.
- Exigencia de hoy ({difficulty}): {tone}
- Hablas en español neutro de Colombia, tuteando: "tú tienes", "mira", "crea". Nunca uses voseo ("tenés", "mirá", "creá").

Tu tarea: escribir el saludo del día a partir de los datos en JSON que te paso.

Reglas:
- Usa solo los datos que te paso. No inventes tareas, fechas ni temas.
- Máximo 110 palabras, en texto plano sin títulos ni negritas.
- Formato: una línea de saludo, luego de 2 a 4 líneas que empiecen con "- " (lo más importante de hoy: pendientes prioritarios y tema de estudio), y una línea de cierre.
- Si hay tareas atrasadas, menciónalo con sarcasmo.
- La racha es solo "racha_dias_seguidos_con_actividad". Si es 0, no hay racha: no digas que sigue viva. Si es 1 o más, presúmela.
- Si se acerca una fecha objetivo (examen), menciona cuántos días faltan."""


def build_context(
    today: date, tasks: list[Task], study: list[Roadmap], pet: PetState, recent: list[dict]
) -> dict:
    open_tasks = [t for t in tasks if not t.done]
    return {
        "fecha": today.isoformat(),
        "dia": WEEKDAYS[today.weekday()],
        "mascota": {
            "humor": pet.mood,
            "energia_0_100": pet.energy,
            "felicidad_0_100": pet.happiness,
            "racha_dias_seguidos_con_actividad": pet.streak,
            "dias_sin_actividad": pet.idle_days,
            "nivel": pet.level,
        },
        "pendientes_prioritarios": [
            {"tarea": t.text, "proyecto": t.project, "atrasada": t.overdue}
            for t in open_tasks[:MAX_TASKS_IN_PROMPT]
        ],
        "total_pendientes": len(open_tasks),
        "total_atrasadas": sum(t.overdue for t in open_tasks),
        "estudio": [
            {
                "roadmap": r.name,
                "fase_actual": r.current.title if r.current else None,
                "temas": [tp.text for tp in r.current.topics][:5] if r.current else [],
                "siguiente_fase": r.next.title if r.next else None,
                "dias_para_fecha_objetivo": r.days_left,
            }
            for r in study
        ],
        "actividad_reciente": [
            {
                "cuando": _relative_day(date.fromisoformat(a["day"]), today),
                "tipo": ACTIVITY_KINDS.get(a["kind"], a["kind"]),
                "que": a["detail"],
            }
            for a in recent[:5]
        ],
    }


def _relative_day(day: date, today: date) -> str:
    delta = (today - day).days
    return {0: "hoy", 1: "ayer"}.get(delta, f"hace {delta} días")


def fallback_briefing(name: str, context: dict) -> str:
    """Template used when Claude is unavailable, so the pet never goes silent."""
    lines = [f"{name} aquí, en modo offline: hoy no hay IA, solo yo leyendo tu lista."]
    for task in context["pendientes_prioritarios"][:3]:
        lines.append(f"- {task['tarea']} ({task['proyecto']})")
    for roadmap in context["estudio"]:
        if roadmap["fase_actual"]:
            lines.append(f"- Estudio: {roadmap['roadmap']} · {roadmap['fase_actual']}")
            break
    lines.append("Dale, que la XP no se farmea sola.")
    return "\n".join(lines)


def generate_briefing(settings: Settings, context: dict, difficulty: Difficulty) -> tuple[str, str]:
    """Return ``(text, source)``; source is ``"claude"`` or ``"fallback"``."""
    if not settings.anthropic_api_key:
        log.warning("ANTHROPIC_API_KEY not set; using fallback briefing")
        return fallback_briefing(settings.pet_name, context), "fallback"

    client = anthropic.Anthropic(api_key=settings.anthropic_api_key, timeout=30.0, max_retries=2)
    system = SYSTEM_PROMPT.format(name=settings.pet_name, difficulty=difficulty, tone=TONE[difficulty])
    try:
        response = client.messages.create(
            model=settings.claude_model,
            max_tokens=1024,
            system=system,
            messages=[{"role": "user", "content": json.dumps(context, ensure_ascii=False, default=str)}],
        )
    except anthropic.AuthenticationError:
        log.error("Claude API: invalid API key")
    except anthropic.NotFoundError:
        log.error("Claude API: model %s not found", settings.claude_model)
    except anthropic.RateLimitError:
        log.warning("Claude API: rate limited")
    except anthropic.APIStatusError as e:
        log.error("Claude API error %s: %s", e.status_code, e.message)
    except anthropic.APIConnectionError:
        log.error("Claude API: connection error")
    else:
        text = "".join(b.text for b in response.content if b.type == "text").strip()
        if response.stop_reason in ("end_turn", "max_tokens") and text:
            log.info("Briefing generated (request %s, %s tokens out)", response._request_id, response.usage.output_tokens)
            return text, "claude"
        log.warning("Claude API: unexpected stop_reason %s", response.stop_reason)
    return fallback_briefing(settings.pet_name, context), "fallback"
